spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/hr_sample
    username: postgres
    password: 1

  liquibase:
    change-log: classpath:db/changelog/changelog-master.xml

mybatis:
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:

    ru.atc.hrsample.service.impl: DEBUG
    org.mybatis: INFO
    ru.atc.hrsample.dao: INFO


